version: "3.7"

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    entrypoint:
      - /home/app/web/entrypoint.prod.sh
  db:
    image: postgres:13-alpine
    volumes:
      - ${PATH_TO_STORAGE}:/var/lib/postgresql/data/:rw
    env_file:
      - ./.env.prod.db
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./services/client
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
