version: '3.8'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.devs
    depends_on:
      - db
    entrypoint:
      - /usr/src/app/entrypoint.sh
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
  client:
    stdin_open: true
    environment: 
      - CHOKIDAR_USEPOLLING=true
    build: ./services/client
    volumes:
      - ./services/client:/app
      - /app/node_modules
  nginx:
    depends_on:
      - web
      - client
    restart: always
    build: ./services/nginx
    ports:
      - '1337:80'
volumes:
  postgres_data:
